name: Publish NPM

run-name: Publish NPM - ${{ github.event.inputs.package }}

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        required: true
        description: 'Which package to release'
        options:
          - artifact
          - attest
          - cache
          - core
          - exec
          - github
          - glob
          - http-client
          - io
          - tool-cache
          

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup repo
        uses: actions/checkout@v4

      - name: verify package exists
        run: ls packages/${{ github.event.inputs.package }}

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: npm install
        run: npm install

      - name: bootstrap
        run: npm run bootstrap

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: pack
        run: npm pack
        working-directory: packages/${{ github.event.inputs.package }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package }}
          path: packages/${{ github.event.inputs.package }}/*.tgz
